#!/usr/bin/python
import sys
import pylab
import h5py
import numpy
import scipy

N = len(sys.argv[1:])

f = h5py.File(sys.argv[1],"r")
time = numpy.array(f["time"])
data = numpy.array(f["data"])
f.close
for arg in sys.argv[2:]:
	f = h5py.File(arg,"r")
	wave = numpy.array(f["data"])
	f.close()

correlation = numpy.real(scipy.ifft(numpy.conj(scipy.fft(wave))*scipy.fft(data)))

ix = numpy.argmax(numpy.abs(correlation))
print correlation[ix]


