#!/usr/bin/python
import os,sys,argparse
import lal
import lalsimulation as lalsim
import matplotlib
matplotlib.rcParams.update({
	"font.size": 10.0,
	"axes.titlesize": 10.0,
	"axes.labelsize": 10.0,
	"xtick.labelsize": 10.0,
	"ytick.labelsize": 10.0,
	"legend.fontsize": 8.0,
	"figure.dpi": 300,
	"savefig.dpi": 300,
	"text.usetex": True,
	"path.simplify": True
})
import pylab, numpy
import waveform_common

m1,m2,s1,s2,dist,secret,data,t,rate,dt = waveform_common.parse()

fig = pylab.figure(figsize=(4.5, 3.0))

pylab.subplot2grid((1,3),(0,0),colspan=2)
pylab.xlim([0,2])
pylab.ylim([-2e-21,2e-21])
if not secret:
	pylab.plot(t, data, linewidth=1, label = '$m_1=%.1f (M_\odot)$ \n $m_2=%.1f (M_\odot)$ \n $s_1=%.2f$ \n $s_2=%.2f$ \n $\mathrm{dist}=%.0f (\mathrm{Mpc})$' % (m1,m2,s1,s2,dist))
else:
	pylab.plot(t, data, linewidth=1, label = '$m_1=??? (M_\odot)$ \n $m_2=??? (M_\odot)$ \n $s_1=???$ \n $s_2=???$ \n $\mathrm{dist}=??? (\mathrm{Mpc})$')
pylab.legend(bbox_to_anchor=(1.05, 1), loc=2, borderaxespad=0)
pylab.xlabel("$\mathrm{time (s)}$")
pylab.ylabel("$\mathrm{strain}$")
fig.tight_layout()
pylab.grid()
if not secret:
	pylab.savefig("wave_%.1f_%.1f_%.2f_%.2f_%.0f.pdf" % (m1,m2,s1,s2,dist))
else:
	pylab.savefig("wave_secret_%d.pdf" % (secret))

