#!/usr/bin/python
import sys
import pylab
import h5py
import numpy

N = len(sys.argv[1:])

f = h5py.File(sys.argv[1],"r")
time = numpy.array(f["time"])
data = numpy.array(f["waveform"])
f.close
for arg in sys.argv[2:]:
	f = h5py.File(arg,"r")
	data += numpy.array(f["waveform"])
	f.close()

data /= N
fig = pylab.figure(figsize=(4.5, 3.0))
pylab.subplot2grid((1,3),(0,0),colspan=2)
pylab.xlim([0,2])
pylab.ylim([-2e-21,2e-21])
pylab.plot(time, data, linewidth=1, label = 'averaged data set')
pylab.legend(bbox_to_anchor=(1.05, 1), loc=2, borderaxespad=0)
pylab.xlabel("$\mathrm{time (s)}$")
pylab.ylabel("$\mathrm{strain}$")
fig.tight_layout()
pylab.grid()
pylab.show()
