#!/usr/bin/python
import os,sys,argparse
import lal
import lalsimulation as lalsim
import numpy
import wave
import waveform_common
import h5py

m1,m2,s1,s2,dist,secret,data,t,rate,dt,noise_amp,max_amp = waveform_common.parse()

data+=numpy.random.randn(len(data))*noise_amp

if not secret:
	f = h5py.File("wave_noise_%.1f_%.1f_%.2f_%.2f_%.0f.hd5" % (m1,m2,s1,s2,dist), "w")
else:
	f = h5py.File("wave_noise_secret_%d.hd5" % (secret,), "w")
dset1 = f.create_dataset("waveform", (len(t),), dtype='f')
dset1[:] = data 
dset2 = f.create_dataset("time", (len(t),), dtype='f')
dset2[:] = t
f.close()
