#!/usr/bin/python
import os,sys,argparse
import lal
import lalsimulation as lalsim
import numpy
import wave
import waveform_common
import h5py

# FIXME don't hard code these values
rate = 4096
dur = 4
noise_amp = 2e-22
if len(sys.argv) < 2:
	raise ValueError("Must give an integer on the command line")
seed = int(sys.argv[1])
numpy.random.seed(seed)
t = numpy.arange(rate * dur) / (1.*rate)
data = numpy.random.randn(rate * dur)*noise_amp
f = h5py.File("noise_%d.hd5" % seed, "w")
dset1 = f.create_dataset("data", (len(t),), dtype='f')
dset1[:] = data 
dset2 = f.create_dataset("time", (len(t),), dtype='f')
dset2[:] = t
f.close()
